### ISSUE TITLE
Large  background values with aperture_stats_tbl

### ISSUE THREAD

**Issue by Gabriel-p** [spacetelescope/wfc3_photometry#2]
For fixed data and `bg_apertures` values, the background obtained with:

    bg_phot = aperture_stats_tbl(data, bg_apertures, sigma_clip=True)
    bg_phot['aperture_median']

is almost twice as large as the values obtained with

```
bg_phot = aperture_photometry(data, bg_apertures)
bg_phot['aperture_sum'] / bg_apertures.area()
```

Shouldn't these values be equivalent?

**Comment by Vb2341** [comment]
In most cases, yeah I would think so.  However, the whole reason I created the background tools are for when the out-of-the-box mean isn't a great statistic.  

Perhaps you have some rather low-valued pixels dragging down the mean?  You can try looking at `bg_phot['aperture_mean']` and seeing how that compares.  If it's sigma clipped, it could just be getting rid of the low values.

**Comment by Gabriel-p** [comment]
I tried using 

```
bg_phot = aperture_stats_tbl(data, bg_apertures, sigma_clip=False)
bckg1 = bg_phot['aperture_mean']
```

and compared to

```
bg_phot = aperture_photometry(data, bg_apertures)
bckg2 = bg_phot['aperture_sum'] / bg_apertures.area()
```

and this is what I've found

![figure_1](https://user-images.githubusercontent.com/6054951/35512083-329bb588-04dd-11e8-8396-7d3d730710e6.png)

For `bckg2<5` `bckg1` gives larger values, but after that the trend mostly inverts and `bckg2` starts giving systematically larger values. These strange trends notwithstanding, the overall median of the differences is rather low `np.median(bckg2-bckg1)~-0.014`.

Is this behavior expected?

**Comment by Vb2341** [comment]
I think thats very dependent on your data, but maybe not.

One thing that my code does is use **any** pixel touched by the annulus to compute the statistics.  Another way of saying that is that the statistics computed in the annulus are **NOT** weighted (in photutils the aperture_sum/background mean is weighted by the overlap between a given pixel and the aperture).  I don't do the weighted statistics as they seem to produce results quite a bit faster, and a weighted median isn't trivial. 

It could be that by not using weights, since the pixels at the outer edge of the annulus give more weight than in the weighted case, the aperture mean is pushed lower.  This would naturally be the case if your annulus encompasses some fraction of the PSF.  Or it could be that the sigma clipping done by my code clips out some of your high pixels (whereas photutils does not).  `aperture_stats_tbl` outputs the number of pixels actually used in my measurements, so comparing that to the PhotUtils area could show if my code clips out too many pixels.

In general, it's hard to say.  It's hard for me to see the same thing, as when I use the mean computed by PhotUtils, I'm dominated by the noise, _for my data_.

**Comment by Gabriel-p** [comment]
Thank you @Vb2341
